// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDB5SIMgSqlNWT-LDUGi_VpWggSbmzg4I',
    appId: '1:160196194485:web:2b9e912bfc8f6bc283cefc',
    messagingSenderId: '160196194485',
    projectId: 'yasartscada',
    authDomain: 'yasartscada.firebaseapp.com',
    storageBucket: 'yasartscada.firebasestorage.app',
    measurementId: 'G-EWBEXMFDS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAIjiHVLfheTTuUrzTbjP1dzGuwjCkeE8',
    appId: '1:160196194485:android:5d8540faf81c16aa83cefc',
    messagingSenderId: '160196194485',
    projectId: 'yasartscada',
    storageBucket: 'yasartscada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCStFPluA19O8GyFPnYVevZmWrtN9kzqBI',
    appId: '1:160196194485:ios:109caef5a4af7b7c83cefc',
    messagingSenderId: '160196194485',
    projectId: 'yasartscada',
    storageBucket: 'yasartscada.firebasestorage.app',
    iosBundleId: 'com.example.yasartFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCStFPluA19O8GyFPnYVevZmWrtN9kzqBI',
    appId: '1:160196194485:ios:109caef5a4af7b7c83cefc',
    messagingSenderId: '160196194485',
    projectId: 'yasartscada',
    storageBucket: 'yasartscada.firebasestorage.app',
    iosBundleId: 'com.example.yasartFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDB5SIMgSqlNWT-LDUGi_VpWggSbmzg4I',
    appId: '1:160196194485:web:59d2093642569a6183cefc',
    messagingSenderId: '160196194485',
    projectId: 'yasartscada',
    authDomain: 'yasartscada.firebaseapp.com',
    storageBucket: 'yasartscada.firebasestorage.app',
    measurementId: 'G-6MZZ2PWWST',
  );
}
